
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Tue May 11 20:19:34 CST 2021
//----------------------------------------------------

package Analizador;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int EXPR = 25;
  public static final int CONTINUE = 31;
  public static final int INCR = 34;
  public static final int FOR = 33;
  public static final int IDENTIFICADOR = 42;
  public static final int NOT = 18;
  public static final int MENORIGUAL = 11;
  public static final int AND = 16;
  public static final int IGUAL = 13;
  public static final int AGRUPACION = 38;
  public static final int IN = 21;
  public static final int OR = 17;
  public static final int CC = 15;
  public static final int IF = 26;
  public static final int CA = 14;
  public static final int MAYORIGUAL = 12;
  public static final int EOF = 0;
  public static final int ASIG = 37;
  public static final int RETURN = 36;
  public static final int error = 1;
  public static final int DIGITO = 40;
  public static final int COMENTARIO = 39;
  public static final int MENOS = 5;
  public static final int MENOR = 9;
  public static final int MOD = 8;
  public static final int DIGITODECIMAL = 41;
  public static final int BREAK = 32;
  public static final int EQ = 19;
  public static final int ERROR = 43;
  public static final int SWITCH = 28;
  public static final int MAYOR = 10;
  public static final int LLC = 3;
  public static final int PUTS = 24;
  public static final int LLA = 2;
  public static final int ELSE = 27;
  public static final int WHILE = 30;
  public static final int NI = 22;
  public static final int DEFAULT = 29;
  public static final int NE = 20;
  public static final int PROC = 35;
  public static final int DIVISION = 7;
  public static final int SET = 23;
  public static final int MULTIPLICACION = 6;
  public static final int MAS = 4;
}

